# Generated by Django 4.1.7 on 2023-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypolygon',
            name='humidity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mypolygon',
            name='temperature',
            field=models.BigIntegerField(default=0),
        ),
    ]
