# Generated by Django 4.1.7 on 2023-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_mypolygon_humidity_mypolygon_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.BigIntegerField()),
                ('humidity', models.BigIntegerField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mypolygon',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='mypolygon',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='mypolygon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
