# Generated by Django 4.1.7 on 2023-04-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_node_remove_mypolygon_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='id',
            new_name='IdNode',
        ),
    ]
