# Generated by Django 4.1.7 on 2023-04-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_id_node_idnode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypolygon',
            old_name='id',
            new_name='idPolygone',
        ),
    ]
