# Generated by Django 4.1.7 on 2023-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_id_mypolygon_idpolygone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypolygon',
            name='namePolygone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
