# Generated by Django 4.1.7 on 2023-04-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_mypolygon_namepolygone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypolygon',
            name='namePolygone',
        ),
    ]
