# Generated by Django 4.1.7 on 2023-04-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_mypolygon_namepolygone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypolygon',
            name='client',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
