# Generated by Django 4.1.7 on 2023-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_mypolygon_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='published_date',
        ),
        migrations.AddField(
            model_name='node',
            name='wind',
            field=models.BigIntegerField(default=0),
        ),
    ]
