# Generated by Django 4.1.7 on 2023-04-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_node_published_date_node_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypolygon',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.node'),
        ),
    ]
