# Generated by Django 4.1.7 on 2023-04-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_mypolygon_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node',
            new_name='Datas',
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='IdNode',
            new_name='IdDatas',
        ),
        migrations.RemoveField(
            model_name='mypolygon',
            name='node',
        ),
    ]
