# Generated by Django 4.1.7 on 2023-04-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_rename_node_datas_rename_idnode_datas_iddatas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('Idnode', models.AutoField(primary_key=True, serialize=False)),
                ('Sensors', models.CharField(max_length=50, null=True)),
                ('RSSI', models.BigIntegerField()),
                ('Battery_value', models.BigIntegerField()),
                ('Polygone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='map.mypolygon')),
            ],
        ),
        migrations.AddField(
            model_name='datas',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='map.nodes'),
        ),
    ]
