# Generated by Django 4.1.7 on 2023-04-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('map', '0013_nodes_datas_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('IdDatas', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.BigIntegerField()),
                ('humidity', models.BigIntegerField()),
                ('wind', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('Idnode', models.AutoField(primary_key=True, serialize=False)),
                ('Sensors', models.CharField(max_length=50, null=True)),
                ('RSSI', models.BigIntegerField()),
                ('Battery_value', models.BigIntegerField()),
                ('Data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='map.data')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('idPoject', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='Polygone',
        ),
        migrations.RemoveField(
            model_name='mypolygon',
            name='status',
        ),
        migrations.DeleteModel(
            name='Datas',
        ),
        migrations.DeleteModel(
            name='Nodes',
        ),
        migrations.AddField(
            model_name='project',
            name='Polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.mypolygon'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='signup.client'),
        ),
        migrations.AddField(
            model_name='mypolygon',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.node'),
        ),
    ]
