# Generated by Django 4.1.7 on 2023-04-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_data_node_project_remove_nodes_polygone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='IdDatas',
            new_name='IdData',
        ),
        migrations.RemoveField(
            model_name='mypolygon',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mypolygon',
            name='supervisor',
        ),
    ]
