# Generated by Django 4.1.7 on 2023-04-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_rename_iddatas_data_iddata_remove_mypolygon_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='idPoject',
            new_name='idProject',
        ),
    ]
