# Generated by Django 4.1.7 on 2023-04-06 22:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_rename_idpoject_project_idproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
