# Generated by Django 4.1.7 on 2023-04-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_node_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='Battery_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='RSSI',
            field=models.BigIntegerField(null=True),
        ),
    ]
