# Generated by Django 4.1.7 on 2023-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_alter_node_battery_value_alter_node_rssi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypolygon',
            name='WFI',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mypolygon',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ref',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
