# Generated by Django 4.1.7 on 2023-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_mypolygon_wfi_mypolygon_status_node_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Date_start',
            field=models.DateField(null=True),
        ),
    ]
