# Generated by Django 4.1.7 on 2023-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_project_date_end_project_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='RSSI',
            field=models.BigIntegerField(default=55),
        ),
    ]
