# Generated by Django 4.1.7 on 2023-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_alter_node_rssi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='RSSI',
            field=models.BigIntegerField(null=True),
        ),
    ]
