# Generated by Django 4.1.7 on 2023-04-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_node_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypolygon',
            old_name='WFI',
            new_name='FWI',
        ),
    ]
