# Generated by Django 4.1.7 on 2023-04-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_alter_mypolygon_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypolygon',
            name='node',
        ),
        migrations.AddField(
            model_name='node',
            name='polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='map.mypolygon'),
        ),
    ]
