# Generated by Django 4.1.7 on 2023-04-12 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_remove_node_data_data_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='node',
        ),
        migrations.AddField(
            model_name='node',
            name='Data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='map.data'),
        ),
    ]
