# Generated by Django 4.1.7 on 2023-04-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_remove_data_node_node_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='Data',
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='map.node'),
        ),
    ]
