# Generated by Django 4.1.7 on 2023-04-18 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0031_node_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_MQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='map.node')),
            ],
        ),
        migrations.CreateModel(
            name='Data_MQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='map.data')),
            ],
        ),
    ]
