# Generated by Django 4.1.7 on 2023-04-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQTT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_mqtt',
            name='node',
        ),
        migrations.DeleteModel(
            name='Data_MQTT',
        ),
        migrations.DeleteModel(
            name='Node_MQTT',
        ),
    ]
